# Generated by Django 5.0.2 on 2024-02-15 18:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insurance', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='insurancepolicy',
            options={'verbose_name': 'Insurance policy', 'verbose_name_plural': 'Insurance policies'},
        ),
        migrations.AlterModelOptions(
            name='policystatus',
            options={'verbose_name': 'Policy status', 'verbose_name_plural': 'Policy statuses'},
        ),
        migrations.AlterField(
            model_name='insurancepolicy',
            name='policy_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='insurance.policytype', verbose_name='Policies Type'),
        ),
        migrations.AlterField(
            model_name='insurancepolicy',
            name='status',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='insurance.policystatus', verbose_name='Policies Status'),
        ),
    ]
