# Generated by Django 5.0.2 on 2024-02-29 19:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TUBase', '0001_initial'),
        ('insurance', '0002_alter_insurancepolicy_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='insurancepolicy',
            name='tuBase',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='TUBase.customtubase', verbose_name='Insurance Company'),
        ),
    ]
