# Generated by Django 5.0.2 on 2024-02-21 19:08

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('insurance', '0002_alter_insurancepolicy_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomVehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registration_number', models.CharField(max_length=20)),
                ('vin_number', models.CharField(max_length=17, unique=True, validators=[django.core.validators.MinLengthValidator(17), django.core.validators.MaxLengthValidator(17)])),
                ('make', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=100)),
                ('purchase_date', models.DateField()),
                ('sale_date', models.DateField(blank=True, null=True)),
                ('policy', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='insurance.insurancepolicy')),
            ],
        ),
    ]
