# Generated by Django 5.0.2 on 2024-02-26 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle', '0003_remove_vehiclestatus_vehicle_status_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehiclestatus',
            name='vehicle_status',
            field=models.CharField(max_length=15, unique=True),
        ),
    ]
