# Generated by Django 5.0.2 on 2024-03-05 18:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TUBase', '0002_customtubase_tubase_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customtubase',
            name='tuBase_id',
        ),
    ]
