# Generated by Django 5.0.2 on 2024-03-26 17:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TUBase', '0003_remove_customtubase_tubase_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customtubase',
            name='id_name',
        ),
    ]
